### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by xraech** [thisago/kiwifyDownload#2]
Can you get me a bit of instructions how to use this? i have a course that i paid, but i wanted to keep the videos in my computer so i can keep doing them even after the subscription period ends...
i kinda get the idea of what the program is doing, but i don't know how to get the master.json that is needed? and if i try to use the source files to get the videos, they're all complaining about privacy, so i guess i need something specific in my cookies for that

**Comment by thisago** [comment]
yeah, you can, but IDK if it's working yet...

to use you need to install Nim (nim-lang.org), then run:
```
nimble install kiwifyDownload
```
you will need the course data JSON.
to get it, you need to open an lesson with dev tools in network tab and find the request that returned the course data.

copy their content to a json file (example: `data.json`)

then run the app using:
```
kiwifyDownload -j data.json -o outDir
```

**Comment by thisago** [comment]
>they're all complaining about privacy, so i guess i need something specific in my cookies for that

yeah, that's correct

**Comment by xraech** [comment]
`PS C:\Users\xendak\source\nim\kiwify> kiwifyDownload.cmd -j master.json -o ./outDir
SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

I'm getting this error, is this due the wrong course.json? or its because the video permission thing?

**Comment by thisago** [comment]
Maybe the JSON structure was changed, if you send me (by email, if you prefer), I can update it for you. They always change it...

**Comment by xraech** [comment]
you prefer via e-mail or here or discord or anything? i can send wherever you want :o

also danm, you reply fast af

it could also be me getting the wrong json too :)

**Comment by thisago** [comment]
maybe email is better

Also, I replied fast by coincidence, I turned on my PC now

**Comment by thisago** [comment]
>it could also be me getting the wrong json too :)

make sure if the json object have all the lessons

**Comment by thisago** [comment]
for some reason my email isn't sending to hotmail, but that one isn't the  course json file, the correct one starts with:
```json
{
  "course": {
    "id": "course id",
    "name": "Course name",
    "config": {
      "slug": "slug",
      "primary_color": "#E84B3C",
      "logo_url": "logo url",
      "comments_enabled": true,
      "comments_auto_publish": false,
      "comments_see_all_classes": false,
      "comments_reply_name": "Author",
      "comments_reply_avatar": "avatar url",
      "premium_members_area": {
        "enabled": false,
        "cover_image_desktop": null,
        "cover_image_mobile": null,
        "cover_video_title_desktop": "title",
        "cover_video_desktop": null,
        "cover_youtube_video_desktop": null,
        "cover_type_desktop": "image",
        "cover_images_desktop": [],
        "cover_video_mobile": null,
        "cover_video_title_mobile": "title",
        "cover_youtube_video_mobile": null,
        "cover_type_mobile": "image",
        "cover_images_mobile": [],
        "area_slider_type": "module",
        "infinite_scroll": false
      }
    },
...
```

**Comment by xraech** [comment]
ok, i got the right one now, but now i'm getting :

`PS C:\Users\xendak\source\nim\kiwify> kiwifyDownload.cmd -j master.json -o ./outDir

Module '0_Boas Vindas'
  Starting download of '0_Boas Vindas - Importante' files
oserr.nim(95)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: Requested command not found: 'wget "https://storage.googleapis.com/assets.kiwify.com.br/QzClopgzMBJpr0u/RODA-DA-VIDA-2023_53700e8b2cb845c3ab859fe204b1df38.xlsx" -O "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx_tmp" && mv "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx_tmp" "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx" '. OS error: [OSError]`

if i do the commands by their own, they work fine, with the script doesn't for some reason

i have both wget and mv working, so if i do

`wget "https://storage.googleapis.com/assets.kiwify.com.br/QzClopgzMBJpr0u/RODA-DA-VIDA-2023_53700e8b2cb845c3ab859fe204b1df38.xlsx" -O "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx_tmp"`


wait for it to finish, and then use
`mv "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx_tmp" "outDir\0_Boas Vindas\0_Boas Vindas - Importante\RODA DA VIDA 2023.xlsx"`

it works fine for some reason


EDIT: 
seems windows was the issue? for some reason, WSL works fine...

**Comment by thisago** [comment]
you need wget in the PATH :(

**Comment by thisago** [comment]
I can't reproduce this in GNU/Linux, soon I'll try on Windows...

**Comment by thisago** [comment]
To I be able to test, I need the course JSON, please send me at my email.
